name: "EMPIRIS Benchmark"
author: "EMPIRIS developers <https://github.com/SWC-EMPIRIS>"
description: "The EMPIRIS benchmarking action"

inputs:
  config_path:
    description: "Path to the EMPIRIS config"
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
