name: Go Microbenchmark

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  benchmark:
    name: Run Go Microbenchmark
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "stable"

      # Step to provision your SUT (optional if running locally in workflow)

      - name: Run Benchmark
        # uses: SWC-EMPIRIS/benchmark-gh-action@main
        uses: ./
        with:
          config_path: empiris.micro.yml
        env:
          api_key: ${{ secrets.EMPIRIS_API_KEY }}
          service_account: ${{ secrets.GOOGLE_CREDENTIALS }}
          ssh_private_key: ${{ secrets.CLOUD_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.CLOUD_SSH_PUBLIC_KEY }}

      - name: Upload benchmark report
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-report
          path: report.json


