name: Example
on:
  push:

jobs:
  benchmark:
    name: Run example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v4
        with:
          go-version: "stable"
      # - uses: hashicorp/setup-terraform@v2

      - name: Run inch
        uses: ./
        env:
          api_key: "pk_3ZJUfUPMDrrrpLrejfAahPe9"
          influx_token: "PdomKtCYz_r7ym9yAcHMzxCA57lwyTkAWiwUbVk4sXePLU5eAckk9J-K6pygGWODRq3t_gFrcsGQNhmJ7Y9HNw=="
          # TODO: This should come from the outputs of a terraform setup
          influx_host: http://localhost:8086
          # influx_host: tf.outputs.influx_ip
